#!/bin/bash
# Script para migrar imagens existentes para o volume persistente no Fly.io

echo "=========================================="
echo "Script de Migração de Imagens para /data/media"
echo "=========================================="
echo ""
echo "Este script deve ser executado DENTRO do container no Fly.io"
echo ""
echo "Passo 1: Conecte-se ao container:"
echo "  fly ssh console -a ecocycle"
echo ""
echo "Passo 2: Execute os comandos abaixo:"
echo ""
echo "# Criar diretórios no volume persistente"
echo "mkdir -p /data/media/produtos"
echo "mkdir -p /data/media/site"
echo ""
echo "# Copiar imagens existentes (se houver)"
echo "if [ -d /usr/src/app/media/produtos ]; then"
echo "  cp -r /usr/src/app/media/produtos/* /data/media/produtos/ 2>/dev/null || true"
echo "fi"
echo ""
echo "if [ -d /usr/src/app/media/site ]; then"
echo "  cp -r /usr/src/app/media/site/* /data/media/site/ 2>/dev/null || true"
echo "fi"
echo ""
echo "# Verificar conteúdo"
echo "ls -la /data/media/"
echo "ls -la /data/media/produtos/"
echo "ls -la /data/media/site/"
echo ""
echo "=========================================="
echo "IMPORTANTE: Depois de fazer isso, você precisa fazer o re-deploy!"
echo "=========================================="
